### ISSUE TITLE
P1P camera not found

### ISSUE THREAD

**Issue by qwasy** [drkpxl/printwatch-card#4]
I installed the latest (1.0.10) version of your addon, filled all my entities into it, but the camera feed is empty.
The second box is the image entity of the camera, which itself works fine.
![Image](https://github.com/user-attachments/assets/ac84225c-c32a-4d3d-ae62-7ddeed14b528)

![Image](https://github.com/user-attachments/assets/16f3452e-c744-440d-bac0-3410c0376f0a)

This is how my ha-bamublab (2.0.41) settings look like:

![Image](https://github.com/user-attachments/assets/4c527465-52de-4f0c-a5f1-7a912b31ae02)

**Comment by drjared88** [comment]
I am having the same issue with my A1. All sensors seem to work but the camera shows printer offline.

![Image](https://github.com/user-attachments/assets/4d970bf5-df79-4a99-84eb-2dfa5491a677)

**Comment by drjared88** [comment]
Made a little progress on this. Added the ‘online_entity’ in my card config to point to the printer online sensor as the default is ‘binary_sesnor.p1s_online’.

The issue now is that the camera image loads but every time it refreshes (1s by default) is flashes ‘Camera unavailable’ for a brief second. For now I updated the refresh interval to 10 seconds to reduce the amount of refreshes.

**Comment by drkpxl** [comment]
It's an issue with the ha-bambulab data source. If you update to their beta it should fix it. (or just wait). They did a large update to get the model preview and it introduced some errors.

Working on a fix to more defensively code around it.

**Comment by drkpxl** [comment]
```yaml
type: custom:printwatch-card
printer_name: P1S
online_entity: binary_sensor.p1s_online
camera_refresh_rate: 1000  # Refresh rate in milliseconds (1 second)
print_status_entity: sensor.p1s_print_status
current_stage_entity: sensor.p1s_current_stage
task_name_entity: sensor.p1s_task_name
progress_entity: sensor.p1s_print_progress
current_layer_entity: sensor.p1s_current_layer
total_layers_entity: sensor.p1s_total_layer_count
remaining_time_entity: sensor.p1s_remaining_time
bed_temp_entity: sensor.p1s_bed_temperature
nozzle_temp_entity: sensor.p1s_nozzle_temperature
bed_target_temp_entity: number.p1s_bed_target_temperature
nozzle_target_temp_entity: number.p1s_nozzle_target_temperature
speed_profile_entity: select.p1s_printing_speed
ams_slot1_entity: sensor.p1s_ams_tray_1
ams_slot2_entity: sensor.p1s_ams_tray_2
ams_slot3_entity: sensor.p1s_ams_tray_3
ams_slot4_entity: sensor.p1s_ams_tray_4
ams_slot5_entity: sensor.p1s_ams_tray_5
...more ams if relevant...
camera_entity: image.p1s_camera
cover_image_entity: image.p1s_cover_image
pause_button_entity: button.p1s_pause_printing
resume_button_entity: button.p1s_resume_printing
stop_button_entity: button.p1s_stop_printing
chamber_light_entity: light.p1s_chamber_light
aux_fan_entity: fan.p1s_aux_fan
print_weight_entity: sensor.p1s_print_weight
print_length_entity: sensor.p1s_print_length
```

Thank you for your patience, this is my first HA card!
